--Write a query to create a table called artists. Should have the following fields
--  1. A artist_id field that serves as a primary key for the table
--  2. A artist_name field with a varying character datatype and a character limit of 255 characters
--  3. A genre_name field with a varying character datatype and a character limit of 100 characters
CREATE TABLE IF NOT EXISTS artists (
    artist_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    artist_name VARCHAR(255),
    genre_name VARCHAR(100)
);