--Write a query to create a table called concerts. It should have the following field:
--  1. A concert_id field that serves as a primary key for the table.
--  2. A concert_name field with varying character datatype, s character limit of 255 characters
--  3. A concert_date field with a date datatype
CREATE TABLE IF NOT EXISTS concerts (
    concert_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    concert_name VARCHAR(255),
    concert_date DATE
);