--Write a query to create a table called songs. It should have the following fields:
--  1. A song_id field that serves as a primary key for the table
--  2. A song_name field with a varying character datatype, a character limit of 100 characters, and a default string value of no song title
--  3. A album_name field with a varying character datatype, a character limit of 100 characters, and a default string value of no album title
--  4. Create a one-to-many relationship between the artists and songs tables. (That is, an artist can be associated with many songs.) Set a constraint on this foreign key so that it cannot be null.
CREATE TABLE IF NOT EXISTS songs (
    song_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_name VARCHAR(100) DEFAULT 'no song title',
    album_name VARCHAR(100) DEFAULT 'no album title',
    artist INTEGER REFERENCES artists(artist_id) NOT NULL
);